### ISSUE TITLE
Setup of Travis CI for project containing rdmd script like content

### ISSUE THREAD

**Issue by fkromer** [fkromer/d-design-patterns#1]
[Building a ("normal") D Project](https://docs.travis-ci.com/user/languages/d/)
Building with *gdc* and *ldc* will not work because they lack `rdmd`.

**Comment by fkromer** [comment]
@ohdatboi Do you know how to configure Travis CI with the single-file dub package approach suggested in #3?

**Comment by ohdatboi** [comment]
@fkromer Yes, I do. I'll submit a PR tomorrow.

**Comment by fkromer** [comment]
@ohdatboi Thanks for your PR.

**Comment by fkromer** [comment]
@ohdatboi After merging the branch ci into the master branch the [builds with OSX seem not to terminate](https://travis-ci.org/fkromer/d-design-patterns/builds/265691142). It would be great if you could have a look at it.

**Comment by ohdatboi** [comment]
@fkromer Build for OS X hasn't been started yet. It takes a while.

**Comment by fkromer** [comment]
@ohdatboi I was confused about the significantly longer build time for OSX.
